const actionTypes = {
  ADD_FAMILY: "ADD_FAMILY",
  ADD_MEMBER: "ADD_MEMBER",
  SUBTRACT_MEMBER: "SUBTRACT_MEMBER",
  UPDATE_MEMBER_INPUT: "UPDATE_MEMBER_INPUT",
  RESET_FAMILY_MEMBERS: "RESET_FAMILY_MEMBERS",
}

export default actionTypes;